"""
Tool 4 - ADF ARM Template Deployment Scripts
=============================================
Validates the ARM template produced by Tool 2, checks parameters for unfilled
placeholders, and generates ready-to-run deployment scripts.

Does NOT connect to Azure or execute any az CLI commands.
The generated scripts are reviewed and run by the user when ready.

Shared resources (Linked Services) are split into a one-time bootstrap script;
per-report resources (Datasets + Pipeline) go into the report-specific script.
This avoids re-deploying shared LS on every pipeline update.

Input  : reports/{report}/adf/arm_template.json
       : reports/{report}/adf/arm_template_parameters.json
Output : reports/{report}/adf/deploy/
             deploy_bootstrap.ps1   (Linked Services - run once per environment)
             deploy_bootstrap.sh
             deploy_{report}.ps1    (Datasets + Pipeline - run per report)
             deploy_{report}.sh
             deployment_checklist.txt

Usage:
  python tool4_adf_deploy.py <report_name> [--rg RESOURCE_GROUP] [-v]

  python tool4_adf_deploy.py BC_BIMIO_267_Daily
  python tool4_adf_deploy.py BC_BIMIO_267_Daily --rg rg-toad-poc-uksouth -v
"""

import argparse
import json
import os
import re
import sys

BASE_DIR    = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
REPORTS_DIR = os.path.join(BASE_DIR, 'reports')

PLACEHOLDER_RE = re.compile(r'^<.+>$')

SHARED_RESOURCE_TYPES = {'linkedservices', 'factories'}


# ─────────────────────────────────────────────────────────────────────────────
# Validation
# ─────────────────────────────────────────────────────────────────────────────

def validate_json(path):
    """Return parsed JSON or raise with a clear message."""
    try:
        with open(path, encoding='utf-8') as f:
            return json.load(f)
    except json.JSONDecodeError as e:
        print(f'  ERROR: Invalid JSON in {path}: {e}')
        sys.exit(1)
    except FileNotFoundError:
        print(f'  ERROR: File not found: {path}')
        sys.exit(1)


def check_parameters(params_data):
    """
    Return (filled, unfilled) lists of parameter names.
    Unfilled = value still matches <your-...> placeholder pattern.
    """
    filled, unfilled = [], []
    for k, v in params_data.get('parameters', {}).items():
        val = str(v.get('value', ''))
        if PLACEHOLDER_RE.match(val):
            unfilled.append((k, val))
        else:
            filled.append((k, val))
    return filled, unfilled


def split_resources(arm_data):
    """
    Split ARM resources into shared (LS + factory) and per-report (DS + pipeline).
    Returns (shared_resources, report_resources).
    """
    shared, report = [], []
    for r in arm_data.get('resources', []):
        rtype = r['type'].split('/')[-1].lower()
        if rtype in SHARED_RESOURCE_TYPES:
            shared.append(r)
        else:
            report.append(r)
    return shared, report


def build_split_arm(base_arm, resources):
    """Return a copy of base_arm with only the given resources."""
    arm = dict(base_arm)
    arm['resources'] = resources
    return arm


# ─────────────────────────────────────────────────────────────────────────────
# Script builders
# ─────────────────────────────────────────────────────────────────────────────

_PS1_HEADER = """\
# =============================================================
# {title}
# Generated by Tool 4 -- review before running.
# =============================================================
# Prerequisites:
#   az CLI installed  : https://learn.microsoft.com/cli/azure/install-azure-cli
#   az login          : run 'az login' or set up a service principal
#   Parameters file   : fill all <your-...> values before running
# =============================================================

$ErrorActionPreference = 'Stop'

# ── Configuration ─────────────────────────────────────────────
$RESOURCE_GROUP = '{rg}'
$LOCATION       = '{location}'
$TEMPLATE       = '{template}'
$PARAMETERS     = '{parameters}'
$DEPLOYMENT     = '{deployment_name}'

# ── Step 1: Ensure resource group exists ──────────────────────
Write-Host "Checking resource group: $RESOURCE_GROUP"
$rgExists = az group exists --name $RESOURCE_GROUP | ConvertFrom-Json
if (-not $rgExists) {{
    Write-Host "Creating resource group $RESOURCE_GROUP in $LOCATION ..."
    az group create --name $RESOURCE_GROUP --location $LOCATION
}}

# ── Step 2: Validate template (offline ARM check) ─────────────
Write-Host "Validating ARM template ..."
az deployment group validate `
    --resource-group $RESOURCE_GROUP `
    --template-file  $TEMPLATE `
    --parameters     $PARAMETERS `
    --name           $DEPLOYMENT

# ── Step 3: What-if preview (shows planned changes) ───────────
# Uncomment to preview before deploying:
# az deployment group what-if `
#     --resource-group $RESOURCE_GROUP `
#     --template-file  $TEMPLATE `
#     --parameters     $PARAMETERS

# ── Step 4: Deploy ────────────────────────────────────────────
Write-Host "Deploying: $DEPLOYMENT ..."
az deployment group create `
    --resource-group $RESOURCE_GROUP `
    --template-file  $TEMPLATE `
    --parameters     $PARAMETERS `
    --name           $DEPLOYMENT `
    --mode           Incremental

Write-Host "Done: $DEPLOYMENT"
"""

_SH_HEADER = """\
#!/usr/bin/env bash
# =============================================================
# {title}
# Generated by Tool 4 -- review before running.
# =============================================================
# Prerequisites:
#   az CLI installed  : https://learn.microsoft.com/cli/azure/install-azure-cli
#   az login          : run 'az login' or set up a service principal
#   Parameters file   : fill all <your-...> values before running
# =============================================================

set -euo pipefail

# -- Configuration --------------------------------------------
RESOURCE_GROUP="{rg}"
LOCATION="{location}"
TEMPLATE="{template}"
PARAMETERS="{parameters}"
DEPLOYMENT="{deployment_name}"

# -- Step 1: Ensure resource group exists ---------------------
echo "Checking resource group: $RESOURCE_GROUP"
if ! az group exists --name "$RESOURCE_GROUP" | grep -q true; then
    echo "Creating resource group $RESOURCE_GROUP in $LOCATION ..."
    az group create --name "$RESOURCE_GROUP" --location "$LOCATION"
fi

# -- Step 2: Validate template (offline ARM check) ------------
echo "Validating ARM template ..."
az deployment group validate \\
    --resource-group "$RESOURCE_GROUP" \\
    --template-file  "$TEMPLATE" \\
    --parameters     "@$PARAMETERS" \\
    --name           "$DEPLOYMENT"

# -- Step 3: What-if preview (shows planned changes) ----------
# Uncomment to preview before deploying:
# az deployment group what-if \\
#     --resource-group "$RESOURCE_GROUP" \\
#     --template-file  "$TEMPLATE" \\
#     --parameters     "@$PARAMETERS"

# -- Step 4: Deploy -------------------------------------------
echo "Deploying: $DEPLOYMENT ..."
az deployment group create \\
    --resource-group "$RESOURCE_GROUP" \\
    --template-file  "$TEMPLATE" \\
    --parameters     "@$PARAMETERS" \\
    --name           "$DEPLOYMENT" \\
    --mode           Incremental

echo "Done: $DEPLOYMENT"
"""


def _norm_path(p):
    """Return forward-slash path for use in shell scripts."""
    return p.replace('\\', '/')


def generate_script(title, rg, location, template_path, params_path, deployment_name, out_dir):
    """Write .ps1 and .sh deploy scripts. Returns (ps1_path, sh_path)."""
    base = deployment_name.replace(' ', '_')

    ps1 = _PS1_HEADER.format(
        title=title, rg=rg, location=location,
        template=template_path, parameters=params_path,
        deployment_name=deployment_name
    )
    sh = _SH_HEADER.format(
        title=title, rg=rg, location=location,
        template=_norm_path(template_path), parameters=_norm_path(params_path),
        deployment_name=deployment_name
    )

    ps1_path = os.path.join(out_dir, f'{base}.ps1')
    sh_path  = os.path.join(out_dir, f'{base}.sh')

    with open(ps1_path, 'w', encoding='utf-8') as f:
        f.write(ps1)
    with open(sh_path, 'w', encoding='utf-8') as f:
        f.write(sh)

    return ps1_path, sh_path


# ─────────────────────────────────────────────────────────────────────────────
# Split ARM templates
# ─────────────────────────────────────────────────────────────────────────────

def write_split_templates(arm_data, params_data, adf_dir, report_name):
    """
    Write two ARM templates:
      arm_template_bootstrap.json  -- factory + linked services (deploy once)
      arm_template_report.json     -- datasets + pipeline (deploy per report)

    Both use the same parameters file.
    Returns (bootstrap_path, report_path).
    """
    shared_res, report_res = split_resources(arm_data)

    bootstrap_arm = build_split_arm(arm_data, shared_res)
    report_arm    = build_split_arm(arm_data, report_res)

    bootstrap_path = os.path.join(adf_dir, 'arm_template_bootstrap.json')
    report_path    = os.path.join(adf_dir, 'arm_template_report.json')

    with open(bootstrap_path, 'w', encoding='utf-8') as f:
        json.dump(bootstrap_arm, f, indent=4, ensure_ascii=False)
    with open(report_path, 'w', encoding='utf-8') as f:
        json.dump(report_arm, f, indent=4, ensure_ascii=False)

    return bootstrap_path, report_path


# ─────────────────────────────────────────────────────────────────────────────
# Checklist
# ─────────────────────────────────────────────────────────────────────────────

def build_checklist(report_name, filled, unfilled, arm_data, rg):
    shared_res, report_res = split_resources(arm_data)
    safe = re.sub(r'[^A-Za-z0-9_]', '_', report_name)

    lines = []
    lines.append('=' * 60)
    lines.append(f'DEPLOYMENT CHECKLIST  --  {report_name}')
    lines.append('=' * 60)
    lines.append('')

    lines.append('PARAMETERS STATUS')
    lines.append('-' * 40)
    for k, v in filled:
        lines.append(f'  [OK]  {k:<30} = {v}')
    for k, v in unfilled:
        lines.append(f'  [!!]  {k:<30} = {v}   <-- fill this')
    lines.append('')

    if unfilled:
        lines.append(f'ACTION REQUIRED: Fill {len(unfilled)} parameter(s) in:')
        lines.append(f'  reports/{report_name}/adf/arm_template_parameters.json')
        lines.append('')

    lines.append('RESOURCES TO DEPLOY')
    lines.append('-' * 40)
    lines.append(f'  Bootstrap (run once per environment):')
    for r in shared_res:
        rtype = r['type'].split('/')[-1]
        rname = re.search(r"'([^']+)'$", r.get('name', '')).group(1) if re.search(r"'([^']+)'$", r.get('name', '')) else r.get('name', '')
        lines.append(f'    {rtype:<20}  {rname}')
    lines.append('')
    lines.append(f'  Per-report (run for each report):')
    for r in report_res:
        rtype = r['type'].split('/')[-1]
        rname = re.search(r"'([^']+)'$", r.get('name', '')).group(1) if re.search(r"'([^']+)'$", r.get('name', '')) else r.get('name', '')
        lines.append(f'    {rtype:<20}  {rname}')
    lines.append('')

    lines.append('DEPLOYMENT SCRIPTS')
    lines.append('-' * 40)
    lines.append(f'  1. reports/{report_name}/adf/deploy/deploy_bootstrap.ps1')
    lines.append(f'     (or .sh)   -- run once for the ADF factory + linked services')
    lines.append(f'  2. reports/{report_name}/adf/deploy/deploy_{safe}.ps1')
    lines.append(f'     (or .sh)   -- run for this report\'s datasets + pipeline')
    lines.append('')

    lines.append('RUN ORDER')
    lines.append('-' * 40)
    lines.append('  Step 1  az login  (or set AZURE_CLIENT_ID / SECRET / TENANT env vars)')
    lines.append(f'  Step 2  Run deploy_bootstrap.ps1  (first report only)')
    lines.append(f'  Step 3  Run deploy_{safe}.ps1  (each report)')
    lines.append('')
    lines.append(f'  Resource group: {rg}')
    lines.append(f'  ADF factory   : adf-toad-poc  (from parameters)')
    lines.append('')

    status = 'READY TO DEPLOY' if not unfilled else f'NOT READY  ({len(unfilled)} unfilled parameters)'
    lines.append(f'STATUS: {status}')
    lines.append('=' * 60)

    return '\n'.join(lines)


# ─────────────────────────────────────────────────────────────────────────────
# Orchestration
# ─────────────────────────────────────────────────────────────────────────────

def _load_rg():
    """Read resource_group from poc_azure_config.json if available."""
    cfg = os.path.join(BASE_DIR, 'global', 'poc_azure_config.json')
    if os.path.exists(cfg):
        try:
            with open(cfg, encoding='utf-8') as f:
                return json.load(f).get('resource_group', '<your-resource-group>')
        except Exception:
            pass
    return '<your-resource-group>'


def generate_deploy(report_name, rg=None, verbose=False):
    # Auto-read resource group from config when not explicitly provided
    if not rg or rg == '<your-resource-group>':
        rg = _load_rg()

    adf_dir     = os.path.join(REPORTS_DIR, report_name, 'adf')
    deploy_dir  = os.path.join(adf_dir, 'deploy')
    arm_path    = os.path.join(adf_dir, 'arm_template.json')
    params_path = os.path.join(adf_dir, 'arm_template_parameters.json')

    if not os.path.exists(arm_path):
        print(f'ARM template not found: {arm_path}')
        print('Run Tool 2 first.')
        sys.exit(1)

    print(f'\nTool 4 -- ADF Deployment Scripts')
    print(f'Report   : {report_name}')
    print(f'RG       : {rg}')

    # ── Validate JSON ─────────────────────────────────────────────────────────
    arm_data    = validate_json(arm_path)
    params_data = validate_json(params_path)
    print(f'  JSON   : arm_template.json  OK ({len(arm_data["resources"])} resources)')
    print(f'  JSON   : arm_template_parameters.json  OK')

    # ── Check parameters ──────────────────────────────────────────────────────
    filled, unfilled = check_parameters(params_data)
    print(f'  Params : {len(filled)} filled / {len(unfilled)} need values')

    if verbose:
        for k, v in filled:
            print(f'    [OK]  {k:<30} = {v}')
        for k, v in unfilled:
            print(f'    [!!]  {k:<30} = {v}')

    # ── Write split ARM templates ─────────────────────────────────────────────
    bootstrap_arm, report_arm = write_split_templates(arm_data, params_data, adf_dir, report_name)
    shared_res, report_res = split_resources(arm_data)
    print(f'  Split  : bootstrap ({len(shared_res)} resources)  +  report ({len(report_res)} resources)')

    # ── Generate deployment scripts ───────────────────────────────────────────
    os.makedirs(deploy_dir, exist_ok=True)
    safe = re.sub(r'[^A-Za-z0-9_]', '_', report_name)
    location = params_data['parameters'].get('location', {}).get('value', 'uksouth')

    # Bootstrap scripts (factory + linked services)
    ps1_b, sh_b = generate_script(
        title=f'Bootstrap: ADF Factory + Linked Services  [{report_name}]',
        rg=rg, location=location,
        template_path=bootstrap_arm,
        params_path=params_path,
        deployment_name='deploy_bootstrap',
        out_dir=deploy_dir
    )
    print(f'  Script : deploy_bootstrap.ps1  /  .sh')

    # Report scripts (datasets + pipeline)
    ps1_r, sh_r = generate_script(
        title=f'Report Pipeline: {report_name}',
        rg=rg, location=location,
        template_path=report_arm,
        params_path=params_path,
        deployment_name=f'deploy_{safe}',
        out_dir=deploy_dir
    )
    print(f'  Script : deploy_{safe}.ps1  /  .sh')

    # ── Write checklist ───────────────────────────────────────────────────────
    checklist = build_checklist(report_name, filled, unfilled, arm_data, rg)
    checklist_path = os.path.join(deploy_dir, 'deployment_checklist.txt')
    with open(checklist_path, 'w', encoding='utf-8') as f:
        f.write(checklist)
    print(f'  Check  : deployment_checklist.txt')

    # ── Summary ───────────────────────────────────────────────────────────────
    print(f'\n{checklist}')


def main():
    ap = argparse.ArgumentParser(description='Tool 4 -- ADF ARM Deployment Scripts')
    ap.add_argument('report', help='Report name (folder under reports/)')
    ap.add_argument('--rg', '--resource-group', default='rg-toad-poc-uksouth',
                    help='Azure resource group name (default: rg-toad-poc-uksouth)')
    ap.add_argument('-v', '--verbose', action='store_true',
                    help='Show all parameter values')
    args = ap.parse_args()
    generate_deploy(args.report, rg=args.rg, verbose=args.verbose)


if __name__ == '__main__':
    main()
