# =============================================================
# Blob Upload: Weekly__BIMIO_384 xlsm template
# Generated by Tool 5 -- review before running.
# =============================================================
# Prerequisites:
#   az CLI installed   : https://learn.microsoft.com/cli/azure/install-azure-cli
#   az login           : run 'az login' or set AZURE_STORAGE_KEY env var
#   Template present   : place .xlsm file in report_templates\
# =============================================================
# Blob layout:
#   toad-poc-reports/templates/{filename}.xlsm  <- shared template container
#   weekly-bimio-384/output_csv/                    <- ADF writes CSV here (per-report)
#   weekly-bimio-384/output_Reports/                <- Function writes xlsm here (per-report)
# =============================================================

$ErrorActionPreference = 'Stop'

# -- Configuration -------------------------------------------
$STORAGE_ACCOUNT     = 'sttoadpoc'
$TEMPLATE_CONTAINER  = 'toad-poc-reports'
$OUTPUT_CONTAINER    = 'weekly-bimio-384'
$LOCAL_DIR           = 'C:\Projects\Toad_poc\migration_toolset\report_templates'
$REPORT_NAME         = 'Weekly__BIMIO_384'

# -- Ensure shared template container exists -----------------
Write-Host "Ensuring template container exists: $TEMPLATE_CONTAINER ..."
az storage container create --account-name $STORAGE_ACCOUNT --name $TEMPLATE_CONTAINER --auth-mode login --fail-on-exist $false | Out-Null

# -- Upload template(s) --------------------------------------
# No xlsm templates detected in sanitised XML.

Write-Host "Template uploaded for $REPORT_NAME."
