#!/usr/bin/env bash
# =============================================================
# Blob Upload: Monthly_BIMIO_494 xlsm template
# Generated by Tool 5 -- review before running.
# =============================================================
# Prerequisites:
#   az CLI installed   : https://learn.microsoft.com/cli/azure/install-azure-cli
#   az login           : run 'az login' or set AZURE_STORAGE_KEY env var
#   Template present   : place .xlsm file in report_templates/
# =============================================================
# Blob layout:
#   toad-poc-reports/templates/{filename}.xlsm  <- shared template container
#   monthly-bimio-494/output_csv/                    <- ADF writes CSV here (per-report)
#   monthly-bimio-494/output_Reports/                <- Function writes xlsm here (per-report)
# =============================================================

set -euo pipefail

# -- Configuration -------------------------------------------
STORAGE_ACCOUNT="sttoadpoc"
TEMPLATE_CONTAINER="toad-poc-reports"
OUTPUT_CONTAINER="monthly-bimio-494"
LOCAL_DIR="C:/Projects/Toad_poc/migration_toolset/report_templates"
REPORT_NAME="Monthly_BIMIO_494"

# -- Ensure shared template container exists -----------------
echo "Ensuring template container exists: $TEMPLATE_CONTAINER ..."
az storage container create --account-name "$STORAGE_ACCOUNT" --name "$TEMPLATE_CONTAINER" --auth-mode login --fail-on-exist false > /dev/null

# -- Upload template(s) --------------------------------------
echo "Uploading: templates/BIMIO 494 -  E1, E2, M1 & M2 Created Manually and YTD Enquiries - .xlsm ..."
az storage blob upload \
    --account-name "$STORAGE_ACCOUNT" \
    --container-name "$TEMPLATE_CONTAINER" \
    --name "templates/BIMIO 494 -  E1, E2, M1 & M2 Created Manually and YTD Enquiries - .xlsm" \
    --file "$LOCAL_DIR/BIMIO 494 -  E1, E2, M1 & M2 Created Manually and YTD Enquiries - .xlsm" \
    --auth-mode login \
    --overwrite

echo "Template uploaded for $REPORT_NAME."
