# =============================================================
# Report Pipeline: BC_BIMIO_267_Daily
# Generated by Tool 4 -- review before running.
# =============================================================
# Prerequisites:
#   az CLI installed  : https://learn.microsoft.com/cli/azure/install-azure-cli
#   az login          : run 'az login' or set up a service principal
#   Parameters file   : fill all <your-...> values before running
# =============================================================

$ErrorActionPreference = 'Stop'

# ── Configuration ─────────────────────────────────────────────
$RESOURCE_GROUP = 'rg-toad-poc-uksouth'
$LOCATION       = 'uksouth'
$TEMPLATE       = 'C:\Projects\Toad_poc\migration_toolset\reports\BC_BIMIO_267_Daily\adf\arm_template_report.json'
$PARAMETERS     = 'C:\Projects\Toad_poc\migration_toolset\reports\BC_BIMIO_267_Daily\adf\arm_template_parameters.json'
$DEPLOYMENT     = 'deploy_BC_BIMIO_267_Daily'

# ── Step 1: Ensure resource group exists ──────────────────────
Write-Host "Checking resource group: $RESOURCE_GROUP"
$rgExists = az group exists --name $RESOURCE_GROUP | ConvertFrom-Json
if (-not $rgExists) {
    Write-Host "Creating resource group $RESOURCE_GROUP in $LOCATION ..."
    az group create --name $RESOURCE_GROUP --location $LOCATION
}

# ── Step 2: Validate template (offline ARM check) ─────────────
Write-Host "Validating ARM template ..."
az deployment group validate `
    --resource-group $RESOURCE_GROUP `
    --template-file  $TEMPLATE `
    --parameters     $PARAMETERS `
    --name           $DEPLOYMENT

# ── Step 3: What-if preview (shows planned changes) ───────────
# Uncomment to preview before deploying:
# az deployment group what-if `
#     --resource-group $RESOURCE_GROUP `
#     --template-file  $TEMPLATE `
#     --parameters     $PARAMETERS

# ── Step 4: Deploy ────────────────────────────────────────────
Write-Host "Deploying: $DEPLOYMENT ..."
az deployment group create `
    --resource-group $RESOURCE_GROUP `
    --template-file  $TEMPLATE `
    --parameters     $PARAMETERS `
    --name           $DEPLOYMENT `
    --mode           Incremental

Write-Host "Done: $DEPLOYMENT"
