# =============================================================
# deploy_func.ps1  --  Deploy func-excel-writer to Azure
# Generated by Nxzen Migration Studio -- review before running.
# =============================================================
#
# What this script does:
#   1. Set Azure subscription
#   2. Create Function App (consumption plan, Python 3.11, Linux)
#   3. Enable system-assigned managed identity on the Function App
#   4. Grant the managed identity GET + LIST access to Key Vault
#   5. Set app settings using Key Vault secret references (no plain-text secrets)
#   6. Zip the function code and deploy via az CLI
#
# Prerequisites:
#   - az CLI installed and logged in  (run: az login)
#   - Two secrets already in Key Vault (create them once -- see below):
#       func-sql-connection-string   : full ODBC connection string for config DB
#       func-storage-connection-string : storage account connection string
#
# How to create the Key Vault secrets (run once):
#   $SQL_PASS = az keyvault secret show --vault-name kv-toad-poc --name azuresql-db-password --query value -o tsv
#   az keyvault secret set --vault-name kv-toad-poc --name func-sql-connection-string `
#     --value "Driver={ODBC Driver 18 for SQL Server};Server=tcp:sql-toad-poc.database.windows.net,1433;Database=db-toad-poc;Uid=sqladmin;Pwd=$SQL_PASS;Encrypt=yes;TrustServerCertificate=no;"
#   $STORAGE_KEY = az storage account keys list --account-name sttoadpoc --query "[0].value" -o tsv
#   az keyvault secret set --vault-name kv-toad-poc --name func-storage-connection-string `
#     --value "DefaultEndpointsProtocol=https;AccountName=sttoadpoc;AccountKey=$STORAGE_KEY;EndpointSuffix=core.windows.net"
# =============================================================

$ErrorActionPreference = 'Stop'

# ── Configuration (read from poc_azure_config.json) ──────────
$CONFIG_PATH = Join-Path $PSScriptRoot "..\..\global\poc_azure_config.json"
$cfg = Get-Content $CONFIG_PATH | ConvertFrom-Json

$SUBSCRIPTION  = $cfg.subscription_id
$RESOURCE_GROUP = $cfg.resource_group
$LOCATION       = $cfg.location
$KEYVAULT       = $cfg.keyvault_name
$STORAGE_ACCT   = $cfg.storage_account
$FUNC_APP       = $cfg.func_app_name
$FUNC_DIR       = Join-Path $PSScriptRoot ".."

Write-Host ""
Write-Host "======================================================"
Write-Host "  Deploy: $FUNC_APP"
Write-Host "  RG    : $RESOURCE_GROUP"
Write-Host "  KV    : $KEYVAULT"
Write-Host "======================================================"
Write-Host ""

# ── Step 1: Set subscription ──────────────────────────────────
Write-Host "Step 1: Setting subscription..."
az account set --subscription $SUBSCRIPTION

# ── Step 2: Create Function App ───────────────────────────────
Write-Host "Step 2: Creating Function App (if not exists)..."

$exists = az functionapp show --name $FUNC_APP --resource-group $RESOURCE_GROUP --query name -o tsv 2>$null
if (-not $exists) {
    Write-Host "  Creating $FUNC_APP ..."
    az functionapp create `
        --name              $FUNC_APP `
        --resource-group    $RESOURCE_GROUP `
        --storage-account   $STORAGE_ACCT `
        --consumption-plan-location $LOCATION `
        --runtime           python `
        --runtime-version   3.11 `
        --os-type           Linux `
        --functions-version 4
    Write-Host "  Created: $FUNC_APP"
} else {
    Write-Host "  Already exists: $FUNC_APP"
}

# ── Step 3: Enable managed identity ──────────────────────────
Write-Host "Step 3: Enabling system-assigned managed identity..."
$principalId = az functionapp identity assign `
    --name              $FUNC_APP `
    --resource-group    $RESOURCE_GROUP `
    --query             principalId `
    --output            tsv

Write-Host "  Principal ID: $principalId"

# ── Step 4: Grant Key Vault access ────────────────────────────
Write-Host "Step 4: Granting Key Vault secret access to managed identity..."
az keyvault set-policy `
    --name          $KEYVAULT `
    --object-id     $principalId `
    --secret-permissions get list

# ── Step 5: Set app settings (Key Vault references) ──────────
Write-Host "Step 5: Setting app settings via Key Vault references..."

$KV_URI = "https://$KEYVAULT.vault.azure.net/secrets"

az functionapp config appsettings set `
    --name           $FUNC_APP `
    --resource-group $RESOURCE_GROUP `
    --settings `
        "SQL_CONNECTION_STRING=@Microsoft.KeyVault(SecretUri=$KV_URI/func-sql-connection-string/)" `
        "STORAGE_CONNECTION_STRING=@Microsoft.KeyVault(SecretUri=$KV_URI/func-storage-connection-string/)" `
        "SCM_DO_BUILD_DURING_DEPLOYMENT=true" `
    | Out-Null

Write-Host "  App settings updated (Key Vault references -- no secrets in config)"

# ── Step 6: Zip and deploy function code ─────────────────────
Write-Host "Step 6: Packaging and deploying function code..."

$ZIP_PATH = Join-Path $PSScriptRoot "func_excel_writer.zip"

# Remove stale zip if it exists
if (Test-Path $ZIP_PATH) { Remove-Item $ZIP_PATH }

# Zip function code (exclude deploy/, __pycache__, .venv, local.settings.json)
$exclude = @("deploy", "__pycache__", ".venv", ".python_packages", "local.settings.json", "*.zip")
$files = Get-ChildItem -Path $FUNC_DIR -Exclude $exclude
Compress-Archive -Path $files.FullName -DestinationPath $ZIP_PATH -Force

Write-Host "  Created: $ZIP_PATH"

az functionapp deployment source config-zip `
    --resource-group $RESOURCE_GROUP `
    --name           $FUNC_APP `
    --src            $ZIP_PATH

Write-Host ""
Write-Host "======================================================"
Write-Host "  Deployment complete: $FUNC_APP"
Write-Host ""
Write-Host "  Function URL (for ADF pipeline parameter):"
$FUNC_KEY = az functionapp keys list `
    --name           $FUNC_APP `
    --resource-group $RESOURCE_GROUP `
    --query          "functionKeys.default" `
    --output         tsv
$HOST_NAME = az functionapp show `
    --name           $FUNC_APP `
    --resource-group $RESOURCE_GROUP `
    --query          "defaultHostName" `
    --output         tsv
Write-Host "  https://$HOST_NAME/api/excel_writer?code=$FUNC_KEY"
Write-Host ""
Write-Host "  Set this URL as excel_writer_url in:"
Write-Host "  reports/{report}/adf/arm_template_parameters.json"
Write-Host "======================================================"
