#!/usr/bin/env bash
# =============================================================
# deploy_func.sh  --  Deploy func-excel-writer to Azure
# Generated by Nxzen Migration Studio -- review before running.
# =============================================================
#
# What this script does:
#   1. Set Azure subscription
#   2. Create Function App (consumption plan, Python 3.11, Linux)
#   3. Enable system-assigned managed identity on the Function App
#   4. Grant the managed identity GET + LIST access to Key Vault
#   5. Set app settings using Key Vault secret references (no plain-text secrets)
#   6. Zip the function code and deploy via az CLI
#
# Prerequisites:
#   - az CLI installed and logged in  (run: az login)
#   - Two secrets already in Key Vault (create them once -- see below):
#       func-sql-connection-string     : full ODBC connection string for config DB
#       func-storage-connection-string : storage account connection string
#
# How to create the Key Vault secrets (run once):
#   SQL_PASS=$(az keyvault secret show --vault-name kv-toad-poc --name azuresql-db-password --query value -o tsv)
#   az keyvault secret set --vault-name kv-toad-poc --name func-sql-connection-string \
#     --value "Driver={ODBC Driver 18 for SQL Server};Server=tcp:sql-toad-poc.database.windows.net,1433;Database=db-toad-poc;Uid=sqladmin;Pwd=${SQL_PASS};Encrypt=yes;TrustServerCertificate=no;"
#   STORAGE_KEY=$(az storage account keys list --account-name sttoadpoc --query "[0].value" -o tsv)
#   az keyvault secret set --vault-name kv-toad-poc --name func-storage-connection-string \
#     --value "DefaultEndpointsProtocol=https;AccountName=sttoadpoc;AccountKey=${STORAGE_KEY};EndpointSuffix=core.windows.net"
# =============================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
FUNC_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
CONFIG_PATH="$SCRIPT_DIR/../../global/poc_azure_config.json"

# ── Read configuration ────────────────────────────────────────
SUBSCRIPTION=$(  jq -r '.subscription_id'  "$CONFIG_PATH")
RESOURCE_GROUP=$(jq -r '.resource_group'   "$CONFIG_PATH")
LOCATION=$(      jq -r '.location'         "$CONFIG_PATH")
KEYVAULT=$(      jq -r '.keyvault_name'    "$CONFIG_PATH")
STORAGE_ACCT=$(  jq -r '.storage_account'  "$CONFIG_PATH")
FUNC_APP=$(      jq -r '.func_app_name'    "$CONFIG_PATH")

echo ""
echo "======================================================"
echo "  Deploy: $FUNC_APP"
echo "  RG    : $RESOURCE_GROUP"
echo "  KV    : $KEYVAULT"
echo "======================================================"
echo ""

# ── Step 1: Set subscription ──────────────────────────────────
echo "Step 1: Setting subscription..."
az account set --subscription "$SUBSCRIPTION"

# ── Step 2: Create Function App ───────────────────────────────
echo "Step 2: Creating Function App (if not exists)..."

if ! az functionapp show --name "$FUNC_APP" --resource-group "$RESOURCE_GROUP" --query name -o tsv 2>/dev/null; then
    echo "  Creating $FUNC_APP ..."
    az functionapp create \
        --name                      "$FUNC_APP" \
        --resource-group            "$RESOURCE_GROUP" \
        --storage-account           "$STORAGE_ACCT" \
        --consumption-plan-location "$LOCATION" \
        --runtime                   python \
        --runtime-version           3.11 \
        --os-type                   Linux \
        --functions-version         4
    echo "  Created: $FUNC_APP"
else
    echo "  Already exists: $FUNC_APP"
fi

# ── Step 3: Enable managed identity ──────────────────────────
echo "Step 3: Enabling system-assigned managed identity..."
PRINCIPAL_ID=$(az functionapp identity assign \
    --name           "$FUNC_APP" \
    --resource-group "$RESOURCE_GROUP" \
    --query          principalId \
    --output         tsv)

echo "  Principal ID: $PRINCIPAL_ID"

# ── Step 4: Grant Key Vault access ────────────────────────────
echo "Step 4: Granting Key Vault secret access to managed identity..."
az keyvault set-policy \
    --name               "$KEYVAULT" \
    --object-id          "$PRINCIPAL_ID" \
    --secret-permissions get list

# ── Step 5: Set app settings (Key Vault references) ──────────
echo "Step 5: Setting app settings via Key Vault references..."

KV_URI="https://${KEYVAULT}.vault.azure.net/secrets"

az functionapp config appsettings set \
    --name           "$FUNC_APP" \
    --resource-group "$RESOURCE_GROUP" \
    --settings \
        "SQL_CONNECTION_STRING=@Microsoft.KeyVault(SecretUri=${KV_URI}/func-sql-connection-string/)" \
        "STORAGE_CONNECTION_STRING=@Microsoft.KeyVault(SecretUri=${KV_URI}/func-storage-connection-string/)" \
        "SCM_DO_BUILD_DURING_DEPLOYMENT=true" \
    > /dev/null

echo "  App settings updated (Key Vault references -- no secrets in config)"

# ── Step 6: Zip and deploy function code ─────────────────────
echo "Step 6: Packaging and deploying function code..."

ZIP_PATH="$SCRIPT_DIR/func_excel_writer.zip"

cd "$FUNC_DIR"
zip -r "$ZIP_PATH" . \
    --exclude "deploy/*" \
    --exclude "__pycache__/*" \
    --exclude ".venv/*" \
    --exclude ".python_packages/*" \
    --exclude "local.settings.json" \
    --exclude "*.zip"

echo "  Created: $ZIP_PATH"

az functionapp deployment source config-zip \
    --resource-group "$RESOURCE_GROUP" \
    --name           "$FUNC_APP" \
    --src            "$ZIP_PATH"

# ── Print function URL ────────────────────────────────────────
echo ""
echo "======================================================"
echo "  Deployment complete: $FUNC_APP"
echo ""
echo "  Function URL (for ADF pipeline parameter):"
FUNC_KEY=$(az functionapp keys list \
    --name           "$FUNC_APP" \
    --resource-group "$RESOURCE_GROUP" \
    --query          "functionKeys.default" \
    --output         tsv)
HOST_NAME=$(az functionapp show \
    --name           "$FUNC_APP" \
    --resource-group "$RESOURCE_GROUP" \
    --query          "defaultHostName" \
    --output         tsv)
echo "  https://${HOST_NAME}/api/excel_writer?code=${FUNC_KEY}"
echo ""
echo "  Set this URL as excel_writer_url in:"
echo "  reports/{report}/adf/arm_template_parameters.json"
echo "======================================================"
